<?php

namespace Database\Seeders;

use Exception;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class QuotesSeeder extends Seeder
{
    public function run()
    {
        $quotes = [
            [
                'author_id' => DB::table('m_authors')->where('name', 'ソクラテス')->value('id'),
                'quote_text' => '私が知っているのは、自分が何も知らないということだけだ。',
                'quote_furigana' => 'わたしがしっているのは、じぶんがなにもしらないということだけだ。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ソクラテス')->value('id'),
                'quote_text' => '徳は魂の美しさである。',
                'quote_furigana' => 'とくはたましいのうつくしさである。',
                'category_id' => DB::table('m_categories')->where('name', '魂')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'プラトン')->value('id'),
                'quote_text' => '徳は知識である。',
                'quote_furigana' => 'とくはちしきである。',
                'category_id' => DB::table('m_categories')->where('name', '教養')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'プラトン')->value('id'),
                'quote_text' => '哲学とは、死を学ぶことである。',
                'quote_furigana' => 'てつがくとは、しをまなぶことである。',
                'category_id' => DB::table('m_categories')->where('name', '悟り')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アリストテレス')->value('id'),
                'quote_text' => '幸福とは、活動における徳の実践である。',
                'quote_furigana' => 'こうふくとは、かつどうにおけるとくのじっせんである。',
                'category_id' => DB::table('m_categories')->where('name', '幸福')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アリストテレス')->value('id'),
                'quote_text' => '人間は本質的に社会的な動物である。',
                'quote_furigana' => 'にんげんはほんしつてきにしゃかいてきなどうぶつである。',
                'category_id' => DB::table('m_categories')->where('name', '絆')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '孔子')->value('id'),
                'quote_text' => '学びて時にこれを習う、また説ばしからずや。',
                'quote_furigana' => 'まなびてときにこれをならう、またよろこばしからずや。',
                'category_id' => DB::table('m_categories')->where('name', '学び')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '孔子')->value('id'),
                'quote_text' => '徳のある者は孤独であることがない。必ず仲間がいる。',
                'quote_furigana' => 'とくのあるものはこどくであることがない。かならずなかまがいる。',
                'category_id' => DB::table('m_categories')->where('name', '絆')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '老子')->value('id'),
                'quote_text' => '千里の道も一歩から。',
                'quote_furigana' => 'せんりのみちもいっぽから。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '老子')->value('id'),
                'quote_text' => '柔よく剛を制す。',
                'quote_furigana' => 'じゅうよくごうをせいす。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'デカルト')->value('id'),
                'quote_text' => '我思う、故に我あり。',
                'quote_furigana' => 'われおもう、ゆえにわれあり。',
                'category_id' => DB::table('m_categories')->where('name', '悟り')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'デカルト')->value('id'),
                'quote_text' => '疑うことは、賢い人の特徴である。',
                'quote_furigana' => 'うたがうことは、かしこいひとのとくちょうである。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ニーチェ')->value('id'),
                'quote_text' => '神は死んだ。',
                'quote_furigana' => 'かみはしんだ。',
                'category_id' => DB::table('m_categories')->where('name', '信仰')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ニーチェ')->value('id'),
                'quote_text' => 'それを埋め尽くすに十分な星があるだろう。',
                'quote_furigana' => 'それをうめつくすにじゅうぶんなほしがあるだろう。',
                'category_id' => DB::table('m_categories')->where('name', '宇宙')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'カント')->value('id'),
                'quote_text' => '汝の意思が、常に普遍的な法則となるよう行動せよ。',
                'quote_furigana' => 'なんじのいしが、つねにふへんてきなほうそくとなるようこうどうせよ。',
                'category_id' => DB::table('m_categories')->where('name', '教え')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'カント')->value('id'),
                'quote_text' => '経験のない概念は空虚であり、概念のない経験は盲目である。',
                'quote_furigana' => 'けいけんのないがいねんはくうきょであり、がいねんのないけいけんはもうもくである。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ヘーゲル')->value('id'),
                'quote_text' => '歴史は自由の意識の進展である。',
                'quote_furigana' => 'れきしはじゆうのいしきのしんてんである。',
                'category_id' => DB::table('m_categories')->where('name', '進歩')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ヘーゲル')->value('id'),
                'quote_text' => '理性は現実的であり、現実は理性的である。',
                'quote_furigana' => 'りせいはげんじつてきであり、げんじつはりせいてきである。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ルソー')->value('id'),
                'quote_text' => '人は自由なものとして生まれるが、至る所で鎖に繋がれている。',
                'quote_furigana' => 'ひとはじゆうなものとしてうまれるが、いたるところでくさりにつながれている。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ルソー')->value('id'),
                'quote_text' => '人々が幸福であるとき、政府は不要である。',
                'quote_furigana' => 'ひとびとがこうふくであるとき、せいふはふようである。',
                'category_id' => DB::table('m_categories')->where('name', '幸福')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アルベルト・アインシュタイン')->value('id'),
                'quote_text' => '成功者になろうとするのではなく、価値のある人間になろうとせよ。',
                'quote_furigana' => 'せいこうしゃになろうとするのではなく、かちのあるにんげんになろうとせよ。',
                'category_id' => DB::table('m_categories')->where('name', '成功')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アルベルト・アインシュタイン')->value('id'),
                'quote_text' => '想像力は知識よりも重要だ。それは、限界を超えるからである。',
                'quote_furigana' => 'そうぞうりょくはちしきよりもじゅうようだ。それは、げんかいをこえるからである。',
                'category_id' => DB::table('m_categories')->where('name', '想像力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アイザック・ニュートン')->value('id'),
                'quote_text' => 'もし私が遠くを見渡せているのだとしたら、それは巨人の肩の上に立っているからだ。',
                'quote_furigana' => 'もしわたしがとおくをみわたせているのだとしたら、それはきょじんのかたのうえにたっているからだ。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アイザック・ニュートン')->value('id'),
                'quote_text' => '自然は何も無駄にしない。',
                'quote_furigana' => 'しぜんはなにもむだにしない。',
                'category_id' => DB::table('m_categories')->where('name', '自然')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'チャールズ・ダーウィン')->value('id'),
                'quote_text' => '最も強い種が生き残るのではなく、最も知的な種でもない。変化に対応できる種が生き残るのだ。',
                'quote_furigana' => 'もっともつよいしゅがいきのこるのではなく、もっともちてきなしゅでもない。へんかにたいおうできるしゅがいきのこるのだ。',
                'category_id' => DB::table('m_categories')->where('name', '進歩')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'チャールズ・ダーウィン')->value('id'),
                'quote_text' => '謙虚さは科学の美徳の一つである。',
                'quote_furigana' => 'けんきょさはかがくのびとくのひとつである。',
                'category_id' => DB::table('m_categories')->where('name', '科学')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'スティーブン・ホーキング')->value('id'),
                'quote_text' => '人生は悲劇的でなければならないが、喜劇的でもなければならない。',
                'quote_furigana' => 'じんせいはひげきてきでなければならないが、きげきてきでもなければならない。',
                'category_id' => DB::table('m_categories')->where('name', 'ユーモア')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'スティーブン・ホーキング')->value('id'),
                'quote_text' => '宇宙は理解するための場所であり、恐れる場所ではない。',
                'quote_furigana' => 'うちゅうはりかいするためのばしょであり、おそれるばしょではない。',
                'category_id' => DB::table('m_categories')->where('name', '宇宙')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マリー・キュリー')->value('id'),
                'quote_text' => '私たちが恐れるべきものは何もない。ただ理解すべきものがあるだけだ。',
                'quote_furigana' => 'わたしたちがおそれるべきものはなにもない。ただりかいすべきものがあるだけだ。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マリー・キュリー')->value('id'),
                'quote_text' => '科学は毎日のパンである。',
                'quote_furigana' => 'かがくはまいにちのぱんである。',
                'category_id' => DB::table('m_categories')->where('name', '科学')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ガリレオ・ガリレイ')->value('id'),
                'quote_text' => 'それでも地球は回っている。',
                'quote_furigana' => 'それでもちきゅうはまわっている。',
                'category_id' => DB::table('m_categories')->where('name', '宇宙')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ガリレオ・ガリレイ')->value('id'),
                'quote_text' => '新しい真実を受け入れるのは簡単ではないが、それは必然である。',
                'quote_furigana' => 'あたらしいしんじつをうけいれるのはかんたんではないが、それはひつぜんである。',
                'category_id' => DB::table('m_categories')->where('name', '進歩')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ニコラ・テスラ')->value('id'),
                'quote_text' => '将来は、電気が世界のすべてを変えるだろう。',
                'quote_furigana' => 'しょうらいは、でんきがせかいのすべてをかえるだろう。',
                'category_id' => DB::table('m_categories')->where('name', '技術革新')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ニコラ・テスラ')->value('id'),
                'quote_text' => '人間の偉大さは、物質的な所有物ではなく、精神的な力にある。',
                'quote_furigana' => 'にんげんのいだいさは、ぶっしつてきなしょゆうぶつではなく、せいしんてきなちからにある。',
                'category_id' => DB::table('m_categories')->where('name', '魂')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'トーマス・エジソン')->value('id'),
                'quote_text' => '天才とは1%のひらめきと99%の努力である。',
                'quote_furigana' => 'てんさいとはいちパーセントのひらめきときゅうじゅうきゅうパーセントのどりょくである。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'トーマス・エジソン')->value('id'),
                'quote_text' => '失敗は成功への道である。',
                'quote_furigana' => 'しっぱいはせいこうへのみちである。',
                'category_id' => DB::table('m_categories')->where('name', '成功')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'カール・セーガン')->value('id'),
                'quote_text' => '私たちは、星の塵でできている。',
                'quote_furigana' => 'わたしたちは、ほしのちりでできている。',
                'category_id' => DB::table('m_categories')->where('name', '宇宙')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'カール・セーガン')->value('id'),
                'quote_text' => '科学は、真実を探求する灯である。',
                'quote_furigana' => 'かがくは、しんじつをたんきゅうするあかりである。',
                'category_id' => DB::table('m_categories')->where('name', '科学')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'リチャード・ファインマン')->value('id'),
                'quote_text' => '分からないことを分からないと認めるのは、知識の進歩の第一歩である。',
                'quote_furigana' => 'わからないことをわからないとみとめるのは、ちしきのしんぽのだいいっぽである。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'リチャード・ファインマン')->value('id'),
                'quote_text' => '物事をシンプルにすることが、理解への鍵である。',
                'quote_furigana' => 'ものごとをシンプルにすることが、りかいへのかぎである。',
                'category_id' => DB::table('m_categories')->where('name', '効率化')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウィリアム・シェイクスピア')->value('id'),
                'quote_text' => 'この世は舞台、人は皆役者。',
                'quote_furigana' => 'このよはぶたい、ひとはみなやくしゃ。',
                'category_id' => DB::table('m_categories')->where('name', '表現')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウィリアム・シェイクスピア')->value('id'),
                'quote_text' => '愛は目で見えず、心で見るものだ。',
                'quote_furigana' => 'あいはめでみえず、こころでみるものだ。',
                'category_id' => DB::table('m_categories')->where('name', '愛')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'トルストイ')->value('id'),
                'quote_text' => '幸福は、自分自身と一致することで見つかる。',
                'quote_furigana' => 'こうふくは、じぶんじしんといっちすることでみつかる。',
                'category_id' => DB::table('m_categories')->where('name', '幸福')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'トルストイ')->value('id'),
                'quote_text' => '人生で最も重要な時間は、今この瞬間だ。',
                'quote_furigana' => 'じんせいでもっともじゅうようなじかんは、いまこのしゅんかんだ。',
                'category_id' => DB::table('m_categories')->where('name', '教え')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ドストエフスキー')->value('id'),
                'quote_text' => '人間とは、苦しむことを愛する存在である。',
                'quote_furigana' => 'にんげんとは、くるしむことをあいするそんざいである。',
                'category_id' => DB::table('m_categories')->where('name', '愛')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ドストエフスキー')->value('id'),
                'quote_text' => '地球上に何が起ころうとも、すべてに神の手がある。',
                'quote_furigana' => 'ちきゅうじょうになにがおころうとも、すべてにかみのてがある。',
                'category_id' => DB::table('m_categories')->where('name', '信仰')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ヘミングウェイ')->value('id'),
                'quote_text' => '本当に勇敢な人は、負けても諦めない。',
                'quote_furigana' => 'ほんとうにゆうかんなひとは、まけてもあきらめない。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ヘミングウェイ')->value('id'),
                'quote_text' => '書くことは、痛みを経験することである。',
                'quote_furigana' => 'かくことは、いたみをけいけんすることである。',
                'category_id' => DB::table('m_categories')->where('name', '文学')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マーク・トウェイン')->value('id'),
                'quote_text' => '真実を語ることで、記憶力を節約できる。',
                'quote_furigana' => 'しんじつをかたることで、きおくりょくをせつやくできる。',
                'category_id' => DB::table('m_categories')->where('name', '効率化')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マーク・トウェイン')->value('id'),
                'quote_text' => '一日に一度も笑わなかったら、その日は失われた日である。',
                'quote_furigana' => 'いちにちにいちどもわらわなかったら、そのひはうしなわれたひである。',
                'category_id' => DB::table('m_categories')->where('name', '笑い')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'オスカー・ワイルド')->value('id'),
                'quote_text' => '自分自身でいることは、最も難しいことだ。',
                'quote_furigana' => 'じぶんじしんでいることは、もっともむずかしいことだ。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'オスカー・ワイルド')->value('id'),
                'quote_text' => '人生を楽しむための唯一の方法は、あらゆる束縛から自由になることだ。',
                'quote_furigana' => 'じんせいをたのしむためのゆいいつのほうほうは、あらゆるそくばくからじゆうになることだ。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジェーン・オースティン')->value('id'),
                'quote_text' => '愛はすべてを変える力を持つ。',
                'quote_furigana' => 'あいはすべてをかえるちからをもつ。',
                'category_id' => DB::table('m_categories')->where('name', '愛')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジェーン・オースティン')->value('id'),
                'quote_text' => '幸福とは、自分が誰であるかを知り、それを受け入れることである。',
                'quote_furigana' => 'こうふくとは、じぶんがだれであるかをしり、それをうけいれることである。',
                'category_id' => DB::table('m_categories')->where('name', '幸福')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アガサ・クリスティ')->value('id'),
                'quote_text' => '推理小説を書くというのは、ゲームのようなものだ。',
                'quote_furigana' => 'すいりしょうせつをかくというのは、げーむのようなものだ。',
                'category_id' => DB::table('m_categories')->where('name', '想像力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アガサ・クリスティ')->value('id'),
                'quote_text' => '人生には、想像力の翼が必要だ。',
                'quote_furigana' => 'じんせいには、そうぞうりょくのつばさがひつようだ。',
                'category_id' => DB::table('m_categories')->where('name', '文学')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '村上春樹')->value('id'),
                'quote_text' => '僕たちはどこへ行くのか、そして何をするのか。',
                'quote_furigana' => 'ぼくたちはどこへいくのか、そしてなにをするのか。',
                'category_id' => DB::table('m_categories')->where('name', '想像力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '村上春樹')->value('id'),
                'quote_text' => '傷つけられることは避けられない。それでも進まなければならない。',
                'quote_furigana' => 'きずつけられることはさけられない。それでもすすまなければならない。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '芥川龍之介')->value('id'),
                'quote_text' => '人生は一冊の書物のようだ。',
                'quote_furigana' => 'じんせいはいっさつのしょもつのようだ。',
                'category_id' => DB::table('m_categories')->where('name', '文学')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '芥川龍之介')->value('id'),
                'quote_text' => '成功するには想像力と勇気が必要だ。',
                'quote_furigana' => 'せいこうするにはそうぞうりょくとゆうきがひつようだ。',
                'category_id' => DB::table('m_categories')->where('name', '成功')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'スティーブ・ジョブズ')->value('id'),
                'quote_text' => '革新とは、古いルールを壊すことだ。',
                'quote_furigana' => 'かくしんとは、ふるいるーるをこわすことだ。',
                'category_id' => DB::table('m_categories')->where('name', '技術革新')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'スティーブ・ジョブズ')->value('id'),
                'quote_text' => '自分の時間を無駄にしないことだ。',
                'quote_furigana' => 'じぶんのじかんをむだにしないことだ。',
                'category_id' => DB::table('m_categories')->where('name', '効率化')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ビル・ゲイツ')->value('id'),
                'quote_text' => '未来に向けて準備しよう。昨日の成功に甘んじてはいけない。',
                'quote_furigana' => 'みらいにむけてじゅんびしよう。きのうのせいこうにあまんじてはいけない。',
                'category_id' => DB::table('m_categories')->where('name', '未来')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ビル・ゲイツ')->value('id'),
                'quote_text' => '一番大事なのは、失敗を恐れないことだ。',
                'quote_furigana' => 'いちばんだいじなのは、しっぱいをおそれないことだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウォーレン・バフェット')->value('id'),
                'quote_text' => 'リスクとは、自分が何をしているか分からないことだ。',
                'quote_furigana' => 'りすくとは、じぶんがなにをしているかわからないことだ。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウォーレン・バフェット')->value('id'),
                'quote_text' => '時間はお金よりも価値がある。',
                'quote_furigana' => 'じかんはおかねよりもかちがある。',
                'category_id' => DB::table('m_categories')->where('name', '効率化')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'イーロン・マスク')->value('id'),
                'quote_text' => '大きな目標を持つことは重要だ。',
                'quote_furigana' => 'おおきなもくひょうをもつことはじゅうようだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'イーロン・マスク')->value('id'),
                'quote_text' => '進化のために失敗を恐れる必要はない。',
                'quote_furigana' => 'しんかのためにしっぱいをおそれるひつようはない。',
                'category_id' => DB::table('m_categories')->where('name', '進歩')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'リチャード・ブランソン')->value('id'),
                'quote_text' => 'リスクを取らなければ、大きな報酬は得られない。',
                'quote_furigana' => 'りすくをとらなければ、おおきなほうしゅうはえられない。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'リチャード・ブランソン')->value('id'),
                'quote_text' => '楽しまなければ意味がない。',
                'quote_furigana' => 'たのしまなければいみがない。',
                'category_id' => DB::table('m_categories')->where('name', 'ユーモア')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジェフ・ベゾス')->value('id'),
                'quote_text' => 'お客様を第一に考え、長期的な視野で行動せよ。',
                'quote_furigana' => 'おきゃくさまをだいいちにかんがえ、ちょうきてきなしやでこうどうせよ。',
                'category_id' => DB::table('m_categories')->where('name', 'リーダーシップ')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジェフ・ベゾス')->value('id'),
                'quote_text' => 'イノベーションには失敗がつきものだ。',
                'quote_furigana' => 'いのべーしょんにはしっぱいがつきものだ。',
                'category_id' => DB::table('m_categories')->where('name', '技術革新')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジャック・マー')->value('id'),
                'quote_text' => '信じ続けることで成功が訪れる。',
                'quote_furigana' => 'しんじつづけることでせいこうがおとずれる。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジャック・マー')->value('id'),
                'quote_text' => '失敗は次の成功の種である。',
                'quote_furigana' => 'しっぱいはつぎのせいこうのたねである。',
                'category_id' => DB::table('m_categories')->where('name', '成功')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ピーター・ドラッカー')->value('id'),
                'quote_text' => '管理されないことは、改善されない。',
                'quote_furigana' => 'かんりされないことは、かいぜんされない。',
                'category_id' => DB::table('m_categories')->where('name', '効率化')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'トーマス・フリードマン')->value('id'),
                'quote_text' => 'フラットな世界では、学び続けることが生き残る鍵である。',
                'quote_furigana' => 'ふらっとなせかいでは、まなびつづけることがいきのこるかぎである。',
                'category_id' => DB::table('m_categories')->where('name', '学び')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'トーマス・フリードマン')->value('id'),
                'quote_text' => '変化に対応できるものが未来を掴む。',
                'quote_furigana' => 'へんかにたいおうできるものがみらいをつかむ。',
                'category_id' => DB::table('m_categories')->where('name', '進歩')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アンドリュー・カーネギー')->value('id'),
                'quote_text' => '成功への第一歩は、目標を明確にすることである。',
                'quote_furigana' => 'せいこうへのだいいっぽは、もくひょうをめいかくにすることである。',
                'category_id' => DB::table('m_categories')->where('name', '成功')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アンドリュー・カーネギー')->value('id'),
                'quote_text' => 'チームワークこそが夢を実現する力である。',
                'quote_furigana' => 'ちーむわーくこそがゆめをじつげんするちからである。',
                'category_id' => DB::table('m_categories')->where('name', 'チームワーク')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ミケランジェロ')->value('id'),
                'quote_text' => '私はまだ学んでいる。',
                'quote_furigana' => 'わたしはまだまなんでいる。',
                'category_id' => DB::table('m_categories')->where('name', '学び')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ミケランジェロ')->value('id'),
                'quote_text' => '完璧な美は細部に宿る。',
                'quote_furigana' => 'かんぺきなびはさいぶにやどる。',
                'category_id' => DB::table('m_categories')->where('name', '創造性')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マハトマ・ガンジー')->value('id'),
                'quote_text' => '弱い者ほど相手を許すことができない。許すことは強さの証だ。',
                'quote_furigana' => 'よわいものほどあいてをゆるすことができない。ゆるすことはつよさのあかしだ。',
                'category_id' => DB::table('m_categories')->where('name', '絆')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マハトマ・ガンジー')->value('id'),
                'quote_text' => 'あなたが見たいと思う世界の変化そのものになりなさい。',
                'quote_furigana' => 'あなたがみたいとおもうせかいのへんかそのものになりなさい。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウィンストン・チャーチル')->value('id'),
                'quote_text' => '成功とは、失敗から失敗へと熱意を失わずに進むことである。',
                'quote_furigana' => 'せいこうとは、しっぱいからしっぱいへとねついをうしなわずにすすむことである。',
                'category_id' => DB::table('m_categories')->where('name', '成功')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウィンストン・チャーチル')->value('id'),
                'quote_text' => '困難はチャンスを隠している。',
                'quote_furigana' => 'こんなんはちゃんすをかくしている。',
                'category_id' => DB::table('m_categories')->where('name', '逆境')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マーティン・ルーサー・キングJr.')->value('id'),
                'quote_text' => '私には夢がある。',
                'quote_furigana' => 'わたしにはゆめがある。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マーティン・ルーサー・キングJr.')->value('id'),
                'quote_text' => '不正義がどこに存在しても、それは全ての正義に対する脅威である。',
                'quote_furigana' => 'ふせいぎがどこにそんざいしても、それはすべてのせいぎにたいするきょういである。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジョン・F・ケネディ')->value('id'),
                'quote_text' => '国があなたに何をしてくれるかではなく、あなたが国に何ができるかを問うべきだ。',
                'quote_furigana' => 'くにがあなたになにをしてくれるかではなく、あなたがくにになにができるかをとうべきだ。',
                'category_id' => DB::table('m_categories')->where('name', 'リーダーシップ')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジョン・F・ケネディ')->value('id'),
                'quote_text' => '進歩のための変化が必要だ。',
                'quote_furigana' => 'しんぽのためのへんかがひつようだ。',
                'category_id' => DB::table('m_categories')->where('name', '進歩')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'バラク・オバマ')->value('id'),
                'quote_text' => '変化はあなたから始まる。',
                'quote_furigana' => 'へんかはあなたからはじまる。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'バラク・オバマ')->value('id'),
                'quote_text' => '希望は、最も暗い時間でも光を見る能力である。',
                'quote_furigana' => 'きぼうは、もっともくらいじかんでもひかりをみるのうりょくである。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マルクス')->value('id'),
                'quote_text' => '哲学者たちは世界を様々に解釈してきたに過ぎない。しかし重要なのは、それを変えることである。',
                'quote_furigana' => 'てつがくしゃたちはせかいをさまざまにかいしゃくしてきたにすぎない。しかしじゅうようなのは、それをかえることである。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マルクス')->value('id'),
                'quote_text' => '歴史は繰り返す。一度目は悲劇として、二度目は喜劇として。',
                'quote_furigana' => 'れきしはくりかえす。いちどめはひげきとして、にどめはきげきとして。',
                'category_id' => DB::table('m_categories')->where('name', 'ユーモア')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'チェ・ゲバラ')->value('id'),
                'quote_text' => '現実主義者でありながら、夢想家であることが可能だ。',
                'quote_furigana' => 'げんじつしゅぎしゃでありながら、むそうかであることがかのうだ。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'チェ・ゲバラ')->value('id'),
                'quote_text' => '自由のために戦うことを選んだ。',
                'quote_furigana' => 'じゆうのためにたたかうことをえらんだ。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ナポレオン・ボナパルト')->value('id'),
                'quote_text' => '不可能という言葉は、フランス語には存在しない。',
                'quote_furigana' => 'ふかのうということばは、ふらんすごにはそんざいしない。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ナポレオン・ボナパルト')->value('id'),
                'quote_text' => '戦争は兵士だけでなく、将軍も訓練する。',
                'quote_furigana' => 'せんそうはへいしだけでなく、しょうぐんもくんれんする。',
                'category_id' => DB::table('m_categories')->where('name', 'リーダーシップ')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アンネ・フランク')->value('id'),
                'quote_text' => '人々の心の中にはまだ善が残っていると信じている。',
                'quote_furigana' => 'ひとびとのこころのなかにはまだぜんがのこっているとしんじている。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アンネ・フランク')->value('id'),
                'quote_text' => '希望は、私たちの心の中にある炎である。',
                'quote_furigana' => 'きぼうは、わたしたちのこころのなかにあるほのおである。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'エイブラハム・リンカーン')->value('id'),
                'quote_text' => '人民の人民による人民のための政治。',
                'quote_furigana' => 'じんみんのじんみんによるじんみんのためのせいじ。',
                'category_id' => DB::table('m_categories')->where('name', 'リーダーシップ')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'エイブラハム・リンカーン')->value('id'),
                'quote_text' => '私は準備が整ったときに必ず成功する。',
                'quote_furigana' => 'わたしはじゅんびがととのったときにかならずせいこうする。',
                'category_id' => DB::table('m_categories')->where('name', '成功')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'レオナルド・ダ・ヴィンチ')->value('id'),
                'quote_text' => 'シンプルさこそ究極の洗練である。',
                'quote_furigana' => 'しんぷるさこそうきゅうきょくのせんれんである。',
                'category_id' => DB::table('m_categories')->where('name', '効率化')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'レオナルド・ダ・ヴィンチ')->value('id'),
                'quote_text' => '知識のすべては経験に始まる。',
                'quote_furigana' => 'ちしきのすべてはけいけんにはじまる。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ピカソ')->value('id'),
                'quote_text' => 'すべての子どもはアーティストである。問題は、成長してもアーティストでいられるかどうかだ。',
                'quote_furigana' => 'すべてのこどもはあーてぃすとである。もんだいは、せいちょうしてもあーてぃすとでいられるかどうかだ。',
                'category_id' => DB::table('m_categories')->where('name', '創造性')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ピカソ')->value('id'),
                'quote_text' => 'アートは、現実を洗い流すための魂の手段である。',
                'quote_furigana' => 'あーとは、げんじつをあらいながすためのたましいのしゅだんである。',
                'category_id' => DB::table('m_categories')->where('name', '絵画')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ゴッホ')->value('id'),
                'quote_text' => '夢を見ることを恐れてはいけない。',
                'quote_furigana' => 'ゆめをみることをおそれてはいけない。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ゴッホ')->value('id'),
                'quote_text' => '小さなものにも、すべてに魂がある。',
                'quote_furigana' => 'ちいさなものにも、すべてにたましいがある。',
                'category_id' => DB::table('m_categories')->where('name', '絆')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'クロード・モネ')->value('id'),
                'quote_text' => '光と色が、世界を形作っている。',
                'quote_furigana' => 'ひかりといろが、せかいをかたちづくっている。',
                'category_id' => DB::table('m_categories')->where('name', '絵画')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'クロード・モネ')->value('id'),
                'quote_text' => '私は自然をそのまま描きたいだけだ。',
                'quote_furigana' => 'わたしはしぜんをそのままえがきたいだけだ。',
                'category_id' => DB::table('m_categories')->where('name', '自然')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'サルバドール・ダリ')->value('id'),
                'quote_text' => '私はドラッグそのものだ。私は夢そのものである。',
                'quote_furigana' => 'わたしはどらっぐそのものだ。わたしはゆめそのものである。',
                'category_id' => DB::table('m_categories')->where('name', '創造性')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'サルバドール・ダリ')->value('id'),
                'quote_text' => '狂気は天才の一部である。',
                'quote_furigana' => 'きょうきはてんさいのいちぶである。',
                'category_id' => DB::table('m_categories')->where('name', '想像力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'バッハ')->value('id'),
                'quote_text' => '音楽は、神と人間をつなぐものだ。',
                'quote_furigana' => 'おんがくは、かみとにんげんをつなぐものだ。',
                'category_id' => DB::table('m_categories')->where('name', '音楽')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'バッハ')->value('id'),
                'quote_text' => 'ただ自分の音楽を追求した結果、評価されることになった。',
                'quote_furigana' => 'ただじぶんのおんがくをついきゅうしたけっか、ひょうかされることになった。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'モーツァルト')->value('id'),
                'quote_text' => '音楽は心の平和をもたらす。',
                'quote_furigana' => 'おんがくはこころのへいわをもたらす。',
                'category_id' => DB::table('m_categories')->where('name', '音楽')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'モーツァルト')->value('id'),
                'quote_text' => '天才とは、生まれながらに備わるものだ。',
                'quote_furigana' => 'てんさいとは、うまれながらにそなわるものだ。',
                'category_id' => DB::table('m_categories')->where('name', '創造性')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ベートーベン')->value('id'),
                'quote_text' => '音楽は魂を解き放つ。',
                'quote_furigana' => 'おんがくはたましいをときはなつ。',
                'category_id' => DB::table('m_categories')->where('name', '音楽')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ベートーベン')->value('id'),
                'quote_text' => '困難を克服することが、人間の本質である。',
                'quote_furigana' => 'こんなんをこくふくすることが、にんげんのほんしつである。',
                'category_id' => DB::table('m_categories')->where('name', '逆境')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'フレディ・マーキュリー')->value('id'),
                'quote_text' => '私は伝説を作りたい。',
                'quote_furigana' => 'わたしはでんせつをつくりたい。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'フレディ・マーキュリー')->value('id'),
                'quote_text' => '音楽は私の人生だ。',
                'quote_furigana' => 'おんがくはわたしのじんせいだ。',
                'category_id' => DB::table('m_categories')->where('name', '音楽')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マイケル・ジョーダン')->value('id'),
                'quote_text' => '私は失敗に失敗を重ねたから成功した。',
                'quote_furigana' => 'わたしはしっぱいにしっぱいをかさねたからせいこうした。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マイケル・ジョーダン')->value('id'),
                'quote_text' => '試さなければ、何も得られない。',
                'quote_furigana' => 'ためさなければ、なにもえられない。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'セリーナ・ウィリアムズ')->value('id'),
                'quote_text' => '成功は忍耐と練習から来る。',
                'quote_furigana' => 'せいこうはにんたいとれんしゅうからくる。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'セリーナ・ウィリアムズ')->value('id'),
                'quote_text' => '勝つことがすべてではないが、勝つことは重要だ。',
                'quote_furigana' => 'かつことがすべてではないが、かつことはじゅうようだ。',
                'category_id' => DB::table('m_categories')->where('name', '勝利')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'イチロー')->value('id'),
                'quote_text' => '小さなことを積み重ねることが、とんでもないところに行くただ一つの道だ。',
                'quote_furigana' => 'ちいさなことをつみかさねることが、とんでもないところにいくただひとつのみちだ。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'イチロー')->value('id'),
                'quote_text' => '結果がすべてではない。プロセスが大切だ。',
                'quote_furigana' => 'けっかがすべてではない。ぷろせすがたいせつだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '大谷翔平')->value('id'),
                'quote_text' => '夢を持つことで人生が豊かになる。',
                'quote_furigana' => 'ゆめをもつことでじんせいがゆたかになる。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '大谷翔平')->value('id'),
                'quote_text' => '努力は嘘をつかない。',
                'quote_furigana' => 'どりょくはうそをつかない。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'クリスティアーノ・ロナウド')->value('id'),
                'quote_text' => '才能だけでは不十分だ。努力と犠牲が必要だ。',
                'quote_furigana' => 'さいのうだけではふじゅうぶんだ。どりょくとぎせいがひつようだ。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'クリスティアーノ・ロナウド')->value('id'),
                'quote_text' => '勝つための鍵は、心の強さだ。',
                'quote_furigana' => 'かつためのかぎは、こころのつよさだ。',
                'category_id' => DB::table('m_categories')->where('name', '勝利')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'リオネル・メッシ')->value('id'),
                'quote_text' => '夢を信じて努力を続ければ、夢は実現する。',
                'quote_furigana' => 'ゆめをしんじてどりょくをつづければ、ゆめはじつげんする。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'リオネル・メッシ')->value('id'),
                'quote_text' => '成功は、日々の努力の積み重ねだ。',
                'quote_furigana' => 'せいこうは、ひびのどりょくのつみかさねだ。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'トム・ブレイディ')->value('id'),
                'quote_text' => '成功は、準備と忍耐から生まれる。',
                'quote_furigana' => 'せいこうは、じゅんびとにんたいからうまれる。',
                'category_id' => DB::table('m_categories')->where('name', '忍耐')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'トム・ブレイディ')->value('id'),
                'quote_text' => '競争することは、自分を成長させる機会だ。',
                'quote_furigana' => 'きょうそうすることは、じぶんをせいちょうさせるきかいだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウサイン・ボルト')->value('id'),
                'quote_text' => '夢を叶えるためには、全力で挑む必要がある。',
                'quote_furigana' => 'ゆめをかなえるためには、ぜんりょくでいどむひつようがある。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウサイン・ボルト')->value('id'),
                'quote_text' => 'ゴールを達成する喜びは、すべての努力を価値あるものにする。',
                'quote_furigana' => 'ごーるをたっせいするよろこびは、すべてのどりょくをかちあるものにする。',
                'category_id' => DB::table('m_categories')->where('name', '勝利')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ナディア・コマネチ')->value('id'),
                'quote_text' => '完璧を目指すことが、私を成長させた。',
                'quote_furigana' => 'かんぺきをめざすことが、わたしをせいちょうさせた。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ナディア・コマネチ')->value('id'),
                'quote_text' => 'スポーツは、自分自身を超えるための挑戦だ。',
                'quote_furigana' => 'すぽーつは、じぶんじしんをこえるためのちょうせんだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アンドレ・アガシ')->value('id'),
                'quote_text' => '敗北は成功へのステップである。',
                'quote_furigana' => 'はいぼくはせいこうへのすてっぷである。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アンドレ・アガシ')->value('id'),
                'quote_text' => '努力なくして結果は得られない。',
                'quote_furigana' => 'どりょくなくしてけっかはえられない。',
                'category_id' => DB::table('m_categories')->where('name', '努力')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'イエス・キリスト')->value('id'),
                'quote_text' => '隣人を自分のように愛しなさい。',
                'quote_furigana' => 'りんじんをじぶんのようにあいしなさい。',
                'category_id' => DB::table('m_categories')->where('name', '愛')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'イエス・キリスト')->value('id'),
                'quote_text' => '求めなさい。そうすれば与えられる。',
                'quote_furigana' => 'もとめなさい。そうすればあたえられる。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ブッダ')->value('id'),
                'quote_text' => '全ての生き物に慈悲を持ちなさい。',
                'quote_furigana' => 'すべてのいきものにじひをもちなさい。',
                'category_id' => DB::table('m_categories')->where('name', '生命')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ブッダ')->value('id'),
                'quote_text' => '欲望を手放せば、苦しみから解放される。',
                'quote_furigana' => 'よくぼうをてばなせば、くるしみからかいほうされる。',
                'category_id' => DB::table('m_categories')->where('name', '悟り')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ムハンマド')->value('id'),
                'quote_text' => '知識を求めることは、信者の義務である。',
                'quote_furigana' => 'ちしきをもとめることは、しんじゃのぎむである。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ムハンマド')->value('id'),
                'quote_text' => '他者に親切であることは、信仰の一部である。',
                'quote_furigana' => 'たしゃにしんせつであることは、しんこうのいちぶである。',
                'category_id' => DB::table('m_categories')->where('name', '信仰')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マザー・テレサ')->value('id'),
                'quote_text' => '小さなことにも、偉大な愛を込めなさい。',
                'quote_furigana' => 'ちいさなことにも、いだいなあいをこめなさい。',
                'category_id' => DB::table('m_categories')->where('name', '愛')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'マザー・テレサ')->value('id'),
                'quote_text' => '一番大切なことは、愛することだ。',
                'quote_furigana' => 'いちばんたいせつなことは、あいすることだ。',
                'category_id' => DB::table('m_categories')->where('name', '愛')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '聖フランシスコ')->value('id'),
                'quote_text' => 'まずは平和を作るために、自分自身を変えなさい。',
                'quote_furigana' => 'まずはへいわをつくるために、じぶんじしんをかえなさい。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '聖フランシスコ')->value('id'),
                'quote_text' => '与えることが、受け取ることである。',
                'quote_furigana' => 'あたえることが、うけとることである。',
                'category_id' => DB::table('m_categories')->where('name', '感謝')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ダライ・ラマ14世')->value('id'),
                'quote_text' => '幸せは、自分自身の心から始まる。',
                'quote_furigana' => 'しあわせは、じぶんじしんのこころからはじまる。',
                'category_id' => DB::table('m_categories')->where('name', '幸福')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ダライ・ラマ14世')->value('id'),
                'quote_text' => '他者への思いやりが、世界を平和にする。',
                'quote_furigana' => 'たしゃへのおもいやりが、せかいをへいわにする。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アルバート・シュヴァイツァー')->value('id'),
                'quote_text' => '生命を尊重することが、すべての倫理の基礎である。',
                'quote_furigana' => 'せいめいをそんちょうすることが、すべてのりんりのきそである。',
                'category_id' => DB::table('m_categories')->where('name', '生命')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アルバート・シュヴァイツァー')->value('id'),
                'quote_text' => '幸福は、自分自身を忘れ、他者に尽くすことにある。',
                'quote_furigana' => 'こうふくは、じぶんじしんをわすれ、たしゃにつくすことにある。',
                'category_id' => DB::table('m_categories')->where('name', '幸福')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ラビ・サックス')->value('id'),
                'quote_text' => '希望は、未来に向かう信仰である。',
                'quote_furigana' => 'きぼうは、みらいにむかうしんこうである。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ラビ・サックス')->value('id'),
                'quote_text' => '対話は平和への鍵である。',
                'quote_furigana' => 'たいわはへいわへのかぎである。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'エックハルト・トール')->value('id'),
                'quote_text' => '今という瞬間に完全に存在しなさい。',
                'quote_furigana' => 'いまといゅうしゅんかんにかんぜんにそんざいしなさい。',
                'category_id' => DB::table('m_categories')->where('name', '悟り')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'エックハルト・トール')->value('id'),
                'quote_text' => '心の静寂が、真の力を引き出す。',
                'quote_furigana' => 'こころのせいじゃくが、しんのちからをひきだす。',
                'category_id' => DB::table('m_categories')->where('name', '魂')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'オプラ・ウィンフリー')->value('id'),
                'quote_text' => '感謝は人生を豊かにする。',
                'quote_furigana' => 'かんしゃはじんせいをゆたかにする。',
                'category_id' => DB::table('m_categories')->where('name', '感謝')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'オプラ・ウィンフリー')->value('id'),
                'quote_text' => '夢を信じることが、実現への第一歩である。',
                'quote_furigana' => 'ゆめをしんじることが、じつげんへのだいいっぽである。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アルバート・シュヴァイツァー')->value('id'),
                'quote_text' => '生命を尊重することが、すべての倫理の基礎である。',
                'quote_furigana' => 'せいめいをそんちょうすることが、すべてのりんりのきそである。',
                'category_id' => DB::table('m_categories')->where('name', '生命')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'アルバート・シュヴァイツァー')->value('id'),
                'quote_text' => '幸福は、自分自身を忘れ、他者に尽くすことにある。',
                'quote_furigana' => 'こうふくは、じぶんじしんをわすれ、たしゃにつくすことにある。',
                'category_id' => DB::table('m_categories')->where('name', '幸福')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジョン・ウェスリー')->value('id'),
                'quote_text' => '善を行う機会がある限り、常に行動せよ。',
                'quote_furigana' => 'ぜんをおこなうきかいがあるかぎり、つねにこうどうせよ。',
                'category_id' => DB::table('m_categories')->where('name', '教え')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ジョン・ウェスリー')->value('id'),
                'quote_text' => '世界は、行動する者によって変わる。',
                'quote_furigana' => 'せかいは、こうどうするものによってかわる。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'レディー・ガガ')->value('id'),
                'quote_text' => '自分自身でいることを恐れないで。',
                'quote_furigana' => 'じぶんじしんでいることをおそれないで。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'レディー・ガガ')->value('id'),
                'quote_text' => 'あなたのユニークさが、あなたの力だ。',
                'quote_furigana' => 'あなたのゆにーくさが、あなたのちからだ。',
                'category_id' => DB::table('m_categories')->where('name', '創造性')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'テイラー・スウィフト')->value('id'),
                'quote_text' => '自分を信じれば、すべての夢が叶う。',
                'quote_furigana' => 'じぶんをしんじれば、すべてのゆめがかなう。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'テイラー・スウィフト')->value('id'),
                'quote_text' => '批判は、新しいことに挑戦している証拠だ。',
                'quote_furigana' => 'ひはんは、あたらしいことにちょうせんしているしょうこだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'BTS')->value('id'),
                'quote_text' => '自分を愛することは、自分を見つける第一歩だ。',
                'quote_furigana' => 'じぶんをあいすることは、じぶんをみつけるだいいっぽだ。',
                'category_id' => DB::table('m_categories')->where('name', '愛')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'BTS')->value('id'),
                'quote_text' => '夢を信じて、諦めずに進もう。',
                'quote_furigana' => 'ゆめをしんじて、あきらめずにすすもう。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'キアヌ・リーブス')->value('id'),
                'quote_text' => '人生は困難に満ちているが、それにどう立ち向かうかが大切だ。',
                'quote_furigana' => 'じんせいはこんなんにみちているが、それにどうたちむかうかがたいせつだ。',
                'category_id' => DB::table('m_categories')->where('name', '逆境')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'キアヌ・リーブス')->value('id'),
                'quote_text' => '他者への思いやりが、世界を変える力になる。',
                'quote_furigana' => 'たしゃへのおもいやりが、せかいをかえるちからになる。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'エマ・ワトソン')->value('id'),
                'quote_text' => '自分の声を見つけ、それを使うことが大切だ。',
                'quote_furigana' => 'じぶんのこえをみつけ、それをつかうことがたいせつだ。',
                'category_id' => DB::table('m_categories')->where('name', '表現')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'エマ・ワトソン')->value('id'),
                'quote_text' => '行動は言葉以上の力を持つ。',
                'quote_furigana' => 'こうどうはことばいじょうのちからをもつ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウィル・スミス')->value('id'),
                'quote_text' => '恐怖は、成長の手助けとなる挑戦だ。',
                'quote_furigana' => 'きょうふは、せいちょうのてだすけとなるちょうせんだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウィル・スミス')->value('id'),
                'quote_text' => '自分の人生を形作るのは、自分自身の選択だ。',
                'quote_furigana' => 'じぶんのじんせいをかたちづくるのは、じぶんじしんのせんたくだ。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '小泉進次郎')->value('id'),
                'quote_text' => '未来を変えるには、今を変える勇気が必要だ。',
                'quote_furigana' => 'みらいをかえるには、いまをかえるゆうきがひつようだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '小泉進次郎')->value('id'),
                'quote_text' => '環境を守ることは、次世代への責任だ。',
                'quote_furigana' => 'かんきょうをまもることは、じせだいへのせきにんだ。',
                'category_id' => DB::table('m_categories')->where('name', '環境')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ムンバイの貧困女性活動家')->value('id'),
                'quote_text' => '私たちは声を上げなければならない。それが変化の始まりだ。',
                'quote_furigana' => 'わたしたちはこえをあげなければならない。それがへんかのはじまりだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ムンバイの貧困女性活動家')->value('id'),
                'quote_text' => '教育は私たちに自由をもたらす。',
                'quote_furigana' => 'きょういくはわたしたちにじゆうをもたらす。',
                'category_id' => DB::table('m_categories')->where('name', '学び')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ボブ・ディラン')->value('id'),
                'quote_text' => '風に吹かれて答えを見つける。',
                'quote_furigana' => 'かぜにふかれてこたえをみつける。',
                'category_id' => DB::table('m_categories')->where('name', '自然')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ボブ・ディラン')->value('id'),
                'quote_text' => '音楽は、言葉では表せない感情を伝える。',
                'quote_furigana' => 'おんがくは、ことばではあらわせないかんじょうをつたえる。',
                'category_id' => DB::table('m_categories')->where('name', '音楽')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ダース・ベイダー')->value('id'),
                'quote_text' => '力とは、強さだけでなく、意志を示すものだ。',
                'quote_furigana' => 'ちからとは、つよさだけでなく、いしをしめすものだ。',
                'category_id' => DB::table('m_categories')->where('name', 'リーダーシップ')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ダース・ベイダー')->value('id'),
                'quote_text' => '心の中の闇を乗り越えろ。',
                'quote_furigana' => 'こころのなかのやみをのりこえろ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ハリー・ポッター')->value('id'),
                'quote_text' => '選択こそが、本当の自分を形作る。',
                'quote_furigana' => 'せんたくこそが、ほんとうのじぶんをかたちづくる。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ハリー・ポッター')->value('id'),
                'quote_text' => '勇気は恐怖を乗り越える力だ。',
                'quote_furigana' => 'ゆうきはきょうふをのりこえるちからだ。',
                'category_id' => DB::table('m_categories')->where('name', '挑戦')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ゴルゴ13')->value('id'),
                'quote_text' => '信頼は一瞬で崩れるが、築くには時間がかかる。',
                'quote_furigana' => 'しんらいはいっしゅんでくずれるが、きずくにはじかんがかかる。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ゴルゴ13')->value('id'),
                'quote_text' => 'プロフェッショナルであるとは、常に結果を出すことだ。',
                'quote_furigana' => 'ぷろふぇっしょなるであるとは、つねにけっかをだすことだ。',
                'category_id' => DB::table('m_categories')->where('name', '効率化')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ルパン三世')->value('id'),
                'quote_text' => '自由は、すべてを失う覚悟がある人だけに許される。',
                'quote_furigana' => 'じゆうは、すべてをうしなうかくごがあるひとだけにゆるされる。',
                'category_id' => DB::table('m_categories')->where('name', '調和')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ルパン三世')->value('id'),
                'quote_text' => '計画と即興のバランスが大事だ。',
                'quote_furigana' => 'けいかくとそっきょうのばらんすがだいじだ。',
                'category_id' => DB::table('m_categories')->where('name', '創造性')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'モンキー・D・ルフィ')->value('id'),
                'quote_text' => '仲間がいる限り、俺は負けない！',
                'quote_furigana' => 'なかまがいるかぎり、おれはまけない！',
                'category_id' => DB::table('m_categories')->where('name', '絆')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'モンキー・D・ルフィ')->value('id'),
                'quote_text' => '海賊王に、俺はなる！',
                'quote_furigana' => 'かいぞくおうに、おれはなる！',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],           
            [
                'author_id' => DB::table('m_authors')->where('name', 'シェルロック・ホームズ')->value('id'),
                'quote_text' => 'データがなければ、仮説は空論だ。',
                'quote_furigana' => 'でーたがなければ、かせつはくうろんだ。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'シェルロック・ホームズ')->value('id'),
                'quote_text' => '真実は、必ず一つだ。',
                'quote_furigana' => 'しんじつは、かならずひとつだ。',
                'category_id' => DB::table('m_categories')->where('name', '信頼')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'デスノートのL')->value('id'),
                'quote_text' => '常に相手の一歩先を行く。',
                'quote_furigana' => 'つねにあいてのいっぽさきをいく。',
                'category_id' => DB::table('m_categories')->where('name', '創造性')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'デスノートのL')->value('id'),
                'quote_text' => '論理は感情に勝る。',
                'quote_furigana' => 'ろんりはかんじょうにまさる。',
                'category_id' => DB::table('m_categories')->where('name', '知識')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '手塚治虫')->value('id'),
                'quote_text' => '漫画は、私の言葉であり、私の人生そのものだ。',
                'quote_furigana' => 'まんがは、わたしのことばであり、わたしのじんせいそのものだ。',
                'category_id' => DB::table('m_categories')->where('name', '表現')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', '手塚治虫')->value('id'),
                'quote_text' => '理想を追い求めることが、芸術の本質である。',
                'quote_furigana' => 'りそうをおいもとめることが、げいじゅつのほんしつである。',
                'category_id' => DB::table('m_categories')->where('name', '創造性')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウォルト・ディズニー')->value('id'),
                'quote_text' => '夢を追い続ける勇気が、成功を掴む鍵である。',
                'quote_furigana' => 'ゆめをおいつづけるゆうきが、せいこうをつかむかぎである。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ウォルト・ディズニー')->value('id'),
                'quote_text' => '困難の中にもチャンスは存在する。',
                'quote_furigana' => 'こんなんのなかにもちゃんすはそんざいする。',
                'category_id' => DB::table('m_categories')->where('name', '逆境')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ヘレン・ケラー')->value('id'),
                'quote_text' => '希望を持つことは、暗闇に光を灯すことだ。',
                'quote_furigana' => 'きぼうをもつことは、くらやみにひかりをともすことだ。',
                'category_id' => DB::table('m_categories')->where('name', '希望')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'author_id' => DB::table('m_authors')->where('name', 'ヘレン・ケラー')->value('id'),
                'quote_text' => '一つの扉が閉じるとき、必ず別の扉が開く。',
                'quote_furigana' => 'ひとつのとびらがとじるとき、かならずべつのとびらがひらく。',
                'category_id' => DB::table('m_categories')->where('name', '逆境')->value('id'),
                'created_at' => now(),
                'updated_at' => now(),
            ],           
        ];

        foreach ($quotes as $quote) {
            if (is_null($quote['category_id'])) {
                throw new Exception("Category not found for quote_text: " . $quote['quote_text']);
            }
        
            DB::table('t_quotes')->insert([
                'author_id' => $quote['author_id'],
                'quote_text' => $quote['quote_text'],
                'quote_furigana' => $quote['quote_furigana'],
                'category_id' => $quote['category_id'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}